# Generated by Django 4.2.2 on 2024-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_postagemforumcomentario'),
        ('pages', '0002_alter_blocos_options_conteudo_descricao_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocos',
            name='posts',
            field=models.ManyToManyField(blank=True, to='forum.postagemforum'),
        ),
    ]
