# Generated by Django 4.2.2 on 2024-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_postagemforumcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente.', null=True, unique=True, verbose_name='URL única')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='postagemforum',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_posts', to='forum.category'),
        ),
        migrations.AddField(
            model_name='postagemforum',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_posts', to='forum.tag'),
        ),
    ]
